### ISSUE TITLE
5374のメイン画面の文字色について

### ISSUE THREAD

**Issue by takuya310** [codeforkanazawa-org/5374#68]
Code for Ikomaの佐藤です。
先日、地域のゴミ関係の会議に出ていた方から意見がありました。

会議にて、メイン画面の文字（燃えるごみ、プラスチック など）の文字色が、白だと年配の方に見づらいという意見があったそうです。アクセシビリティ的に水色や緑のところだと思うのですが、こういった意見を踏まえて、デザインガイドラインの改良をしていくのも良いのではないかと思いました。
（例えば、該当箇所はトーンを落とした色にするなど）

私はデザイン専門ではないので、デザイナーさんのご意見などもいただきたいと考えています。よろしくお願いします。

**Comment by kenchif** [comment]
佐藤さん、ご提案ありがとうございます。
Code for Kanazawaの福島です。

デザイナーと検討してみます。また、検討結果をこちらで回答させて頂きますね。

**Comment by kenchif** [comment]
佐藤さん、こんにちは。

本件ですが、デザイナーとも検討しました。
結論としては、デザインガイドラインの改良（変更）はしない方向としました。

とは言っても、変更そのものを否定しているのではなくて、地域によって「文字の太さ」や「フォントの大きさ」などで対応してもらえたらと思っています。
（いまのところ）その部分に関して、ガイドラインで記述することは考えていないということになります。
